# Generated by Django 4.0.5 on 2022-07-02 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35)),
                ('abbreviation', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Waiting_Periods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waiting_period_hours', models.IntegerField()),
                ('counseling_visits', models.IntegerField()),
                ('exception_health', models.CharField(max_length=48)),
                ('waiting_period_notes', models.CharField(max_length=72)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waiting_periods', to='p4_backend_app.state')),
            ],
        ),
        migrations.CreateModel(
            name='laws_for_minors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('below_age', models.IntegerField()),
                ('parental_consent_required', models.BooleanField()),
                ('parental_notification_required', models.BooleanField()),
                ('parents_required', models.IntegerField()),
                ('judicial_bypass_available', models.BooleanField()),
                ('allows_minor_to_consent', models.BooleanField()),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='laws_for_minors', to='p4_backend_app.state')),
            ],
        ),
        migrations.CreateModel(
            name='Insurance_Coverage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requires_coverage', models.BooleanField()),
                ('private_coverage_no_restriction', models.BooleanField()),
                ('private_exception_life', models.BooleanField()),
                ('private_exception_health', models.CharField(max_length=24)),
                ('private_exception_fetal', models.CharField(max_length=24)),
                ('private_exception_rape_or_incest', models.BooleanField()),
                ('exchange_coverage_no_restrictions', models.BooleanField()),
                ('exchange_exception_life', models.BooleanField()),
                ('exchange_exception_health', models.CharField(max_length=28)),
                ('exchange_exception_fetal', models.CharField(max_length=24)),
                ('exchange_exception_rape_or_incest', models.BooleanField()),
                ('exchange_forbids_coverage', models.BooleanField()),
                ('medicaid_coverage_provider_patient_decision', models.BooleanField()),
                ('medicaid_exception_life', models.BooleanField()),
                ('medicaid_exception_health', models.CharField(max_length=12)),
                ('mediacid_exception_fetal', models.CharField(max_length=24)),
                ('mediacid_exception_rape_or_incest', models.BooleanField()),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insurance_coverage', to='p4_backend_app.state')),
            ],
        ),
        migrations.CreateModel(
            name='Gestational_Limits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banned_after_weeks_since_LMP', models.IntegerField()),
                ('exception_life', models.BooleanField()),
                ('exception_health', models.CharField(max_length=23)),
                ('exception_fetal', models.CharField(max_length=23)),
                ('exception_rape_or_incest', models.BooleanField()),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gestational_limits', to='p4_backend_app.state')),
            ],
        ),
    ]
