# This is a basic workflow that is triggered by schedule

name: Run SVG Script

on: workflow_dispatch
#   schedule:
#     - cron: '30 2 * * *'


jobs:
  getData:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]

    steps:
      - name: User Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with: 
          node-version: ${{matrix.node-version}}
          cache: 'npm'
      - name: Install Dependencies
        run: npm ci
      - name: Run Script
        run: npm run get-svg
