# This is a basic workflow that is triggered by schedule

name: Run SVG Script

on:
  schedule:
    - cron: '30 2 * * *'

jobs:
  # This workflow contains a single job called "greet"
  getData:
    name: Get Data
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]

    steps:
    - name: User Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with: 
        node-version: ${{matrix.node-version}}
        cache: 'npm'
    - name: Installing Dependecies
    - run: npm install request-promise node-html-parser
    - name: Run Script
    - run: npm run get-svg
