# This is a basic workflow that is triggered by schedule

name: Run SVG Script

on: workflow_dispatch
#   schedule:
#     - cron: '30 2 * * *'


jobs:
  getData:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: User Node.js
        uses: actions/setup-node@v3
        with: 
          node-version: 16
          cache: 'npm'
      - run: npm ci
      - run: npm run get-svg
